from pylab import (plot, show, xlabel, ylabel, title, legend, xscale, yscale, grid, text, ginput)
from numpy import linspace, logspace, sin, cos
from math import pi
from matplotlib.pyplot import (waitforbuttonpress, draw, axis)

## 1.  Dessiner  la  fonction  sinus  sur  [0 ,2∗pi ]
print("")
print(" 1. Dessiner la fonction sinus sur [0 ,2∗pi ]")
N = 100
x = linspace(0, 2 * pi, N)
y1 = sin(x)
plot(x, y1, 'r-', label="sin")
show()
## 2.  Ajouter un  t i t r e
print("")
print(" 2. Ajouter un titre")
plot(x, y1, 'r-', label="sin")
title("Fonction sinus")
show()
## 3.  Mettre  deux  courbes ,  avec une  legende
print("")
print(" 3. Mettre deux courbes, avec une legende")
y2 = cos(x)
plot(x, y1, 'r-', label="sin")
plot(x, y2, 'b-', label="cos")
legend()
show()
## 4.  Mettre un  label en X,  en Y
print("")
print(" 4. Mettre un label en X, en Y")
y2 = cos(x)
plot(x, y1, 'r-', label="sin")
plot(x, y2, 'b-', label="cos")
xlabel("abscices")
ylabel("ordonne")
title("Fonction cosinus- sinus")
show()
# 5.  Mettre une  echelle  log−logprint( "" )
print("")
print(" 5. Mettre une echelle log−log")
x = logspace(1, 10, 10)
y = logspace(10, 20, 10)
plot(x, y, 'r-', label="log")
xscale("log")
yscale("log")
xlabel("abscices")
ylabel("ordonne")
title("echelle log")
show()
